---
- hosts: localhost
  tasks:
  - name: Adding the header to CSV file 
    lineinfile:
      path: /home/aadmin/ansible/OS_OUTPUT.csv
      line: "HODTNAME,IP ADDRESS,DF -h (mount details)"
      create: yes 
  - name: Collecting hostname 
    shell: "hostname | tr -d '\n'"
    register: hostname_details
  - debug:
      var: hostname_details.stdout
  - name: Collecting IP address
    shell: "hostname -I | awk '{print $1}' | tr -d '\n'"
    register: ip_details
  - debug:
      var: ip_details.stdout
  - name: Collecting the disk storage output
    shell: "df -h | grep -v 'tmpfs'"
    register: df_details
  - debug:
      var: df_details.stdout_lines
  - name: Save data to CSV file 
    lineinfile:
      dest: /home/aadmin/ansible/OS_OUTPUT.csv
      line: "{{ hostname_details.stdout }},{{ip_details.stdout }},{{ df_details.stdout }}"
      delimiter: '\t '
     
     
