---
- hosts: ubuntu
  become: yes
  tasks: 
  - name: Check Apache service restarting on Ubuntu  
    service:
      name: apache2
      state: started
    register: apache_status

  - name: Restart apache service 
    service:
      name: apache2
      state: restarted
    when: apache_status.state != 'started'

  - name: Display the apache2 service status
    debug:
      msg: "Apache2 service is running"
    when: apache_status.state == 'started'
