#!/usr/bin/python3
import os
import csv
import json
from datetime import *


date=date.today()
time1=datetime.now()

filepath=time1.strftime("DAILY_REPORTS_%Y-%m-%d%H%M.csv")
jsonfile="command.json"
with open(jsonfile) as jf:
    my_dict=json.load(jf)
os_name=os.popen(my_dict['os_flavour']).read().strip('\n')
print(os_name)
if os_name == 'ubuntu' or os_name=='kali':
    print("ubuntu/RHEL Os found and we are collecting information , Please wait!!!!")

    #hostname details
    hostname=os.popen(my_dict["hostname"]).read()
    print(hostname)

    #Ip details
    ip=os.popen(my_dict["ip_addr"]).read()
    print(ip)

    #File storage details
    df_details=os.popen(my_dict["df_h"]).read()
    print(df_details)


    #Storin variable into list for inserting CSV data
    header_csv=(my_dict['header_para'])
    header_csv=[str(x) for x in header_csv]
    print(header_csv)

    #Data csv
    data_csv=  [hostname,ip,df_details]

    file1=open(filepath,'a+')
    writer=csv.writer(file1)
    writer.writerow(header_csv)
    writer.writerow(data_csv)
    file1.close()

    print("FIle import successfully from your current directory"+filepath)
else:
    print("Other os found ")
