---
- hosts: all
  gather_facts: true
  tasks:
  - name: Check apache2 version
    shell: apache2 -v
    register: apache2_ver
    when: ansible_os_family == "Debian"
  - name: Printing the apache2 version 
    debug:
      var: apache2_ver.stdout
    when: ansible_os_family == "Debian"
